# Generated by Django 2.2 on 2020-12-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='created_date',
            field=models.DateTimeField(null=True),
        ),
    ]
