# Generated by Django 2.2 on 2020-12-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customers_tracking_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='tracking_code',
            field=models.IntegerField(null=True),
        ),
    ]
