# Generated by Django 2.2 on 2020-12-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201215_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='status',
            field=models.CharField(choices=[(1, 'در حال بررسی'), (2, 'رد درخواست'), (3, 'تایید')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
