# Generated by Django 2.2 on 2020-12-17 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customers_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='update_date',
            field=models.DateTimeField(null=True),
        ),
    ]
